### ISSUE TITLE
Export not working correctly

### ISSUE THREAD

**Issue by undefdev** [pancelor/aseprite-puzzlescript-export#1]
Hey, nice little tool!
Unfortunately exporting doesn't work correctly with the latest version.
It either says 0 tiles exported, or 1 tile exported, while in my ase file there are two tiles.
Tried slices as well.
I used the ARNE16 palette and made a 5x10 image.
This is what it looks like:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/13840966/215715128-38471b7b-6b5f-40d4-ae5c-a3f7aee80454.png">

I used the script from [17dd53e](https://github.com/pancelor/aseprite-puzzlescript-export/commit/17dd53e5db63dd674b31d75bdd4f72303340d35b) instead, which works fine.

**Comment by pancelor** [comment]
I found the bug when the exporter is in "aseprite grid" mode -- thanks for the bug report! I'm pushing the fix now

what do you mean by "Tried slices as well" -- does the exporter not work in slice mode on this image? It works for me (on my fixed version). could you send me the .ase file, if the update doesn't fix it for you?

**Comment by undefdev** [comment]
Unfortunately it doesn't fix it and Github doesn't let me upload .ase files.
I can also reproduce the error with any 5x10 aseprite file with the default palette:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/13840966/216308771-966543d3-054b-45ad-996d-194613c5478f.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/13840966/216308977-61b80011-ae77-4263-8311-bdec289192c0.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/13840966/216308994-484720cb-3576-4790-b83b-56cb6f006787.png">

Same goes for the other grid types (that's what I meant by slices):
<img width="338" alt="image" src="https://user-images.githubusercontent.com/13840966/216309151-1cb933f6-0158-41fe-be25-34fb7aa932d9.png">

If I select active layer only, then it exports 1 tile, but it's incorrect:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/13840966/216309254-a0c3963f-0469-4547-ac6b-cc85268b3cf3.png">
<img width="159" alt="image" src="https://user-images.githubusercontent.com/13840966/216309278-6dfde4a6-70a0-4102-9a0e-d16da8cb2518.png">
```
❯ cat test.txt
───────┬────────────────────────────────────────────────────────────────────────
       │ File: test.txt
───────┼────────────────────────────────────────────────────────────────────────
   1   │ aseprite4
   2   │ #3f3f74
   3   │ .....
   4   │ .....
   5   │ .....
   6   │ .....
   7   │ .0...
   8   │ 
```

**Comment by pancelor** [comment]
oh, I closed this and forgot to check -- did this fix it for you? (thank you for the detailed repro steps btw)
